Repository duplocloud/terraform-provider-duplocloud, pull requests merged in 2024-07, with the labels that each got.

#576 DUPLO-18156 feat: add support for fifo processing for sns topics
  docs/resources/aws_sns_topic.md
  duplocloud/resource_duplo_aws_sns_topic.go
  duplocloud/utils.go
  duplosdk/aws_sns.go
  examples/resources/duplocloud_aws_sns_topic/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 3

#587 DUPLO-16746 plugin crash issue fix
  duplocloud/data_source_duplo_k8_secret.go
  duplocloud/data_source_duplo_k8_secrets.go
Labels: Bug fix, Review effort [1-5]: 2

#578 Duplo-18669 TF Provider - allow "duplocloud_plan_kms" to accept multiple keys
  docs/data-sources/plan_kms_key_v2.md
  docs/data-sources/plan_kms_v2.md
  docs/resources/plan_kms.md
  docs/resources/plan_kms_v2.md
  duplocloud/data_source_duplo_plan.go
  duplocloud/data_source_duplo_plan_kms_v2.go
  duplocloud/provider.go
  duplocloud/resource_duplo_plan_kms.go
  duplocloud/resource_duplo_plan_kms_v2.go
  duplosdk/plan.go
  examples/resources/duplocloud_plan_kms/import.sh
  examples/resources/duplocloud_plan_kms/resource.tf
  examples/resources/duplocloud_plan_kms_v2/import.sh
  examples/resources/duplocloud_plan_kms_v2/resource.tf
Labels: do not merge

#596 DUPLO-18177 feat: add support for enabling/disabling metrics in ASG resources
  CHANGELOG.md
  duplocloud/resource_duplo_asg_profile.go
  duplosdk/asg.go
Labels: enhancement, Review effort [1-5]: 2

#590 DUPLO-18748 feat: add support for healthcheck configuration for Duplo service lbconfigs
  CHANGELOG.md
  docs/resources/duplo_service_lbconfigs.md
  duplocloud/resource_duplo_lbconfigs.go
  examples/resources/duplocloud_duplo_service_lbconfigs/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 3

#591 DUPLO-19011 feat: allow option to force delete ECR repositories from duplo provider
  CHANGELOG.md
  docs/resources/aws_ecr_repository.md
  duplocloud/resource_duplo_aws_ecr_repository.go
  duplosdk/aws_ecr_repository.go
  examples/resources/duplocloud_aws_ecr_repository/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 2

#600 DUPLO-19011 feat: allow option to force delete ECR repositories from duplo provider
  CHANGELOG.md
  docs/resources/aws_ecr_repository.md
  duplocloud/resource_duplo_aws_ecr_repository.go
  duplosdk/aws_ecr_repository.go
  examples/resources/duplocloud_aws_ecr_repository/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 2

#607 DUPLO-18177 fix: add missing adjustment to change in data contract
  CHANGELOG.md
  duplosdk/aws_ecr_repository.go
Labels: Bug fix, Review effort [1-5]: 2
