Repository duplocloud/terraform-provider-duplocloud, pull requests merged in 2024-09, with the labels that each got.

#650 Duplo-20877 RDS Performance Insight
  docs/resources/rds_instance.md
  duplocloud/resource_duplo_rds_instance.go
  duplosdk/rds_instance.go
  examples/resources/duplocloud_rds_instance/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 3

#667 DUPLO-21081 DUPLO-21083: add docs to log delivery config, validate duplicate log types, validate lower verision allowed for log type
  CHANGELOG.md
  docs/resources/ecache_instance.md
  duplocloud/resource_duplo_ecache_instance.go
Labels: documentation, enhancement, Review effort [1-5]: 2

#666 DUPLO-21060 TF:Azure:AgentPool: Resource 'duplocloud_azure_k8_node_pool' allows update of Scale Set Priority
  CHANGELOG.md
  duplocloud/resource_duplo_azure_k8_node_pool.go
Labels: documentation, enhancement, Review effort [1-5]: 2

#665 DUPLO-21059 TF:Azure:AgentPool: Resource duplocloud_azure_k8_node_pool allows update of 'eviction_policy' for 'Scale Set Priority' = 'Spot'
  CHANGELOG.md
  duplocloud/resource_duplo_azure_k8_node_pool.go
Labels: documentation, enhancement, Review effort [1-5]: 2

#659 DUPLO-20967 TF: duplocloud_k8_secret reports diffs even after apply
  CHANGELOG.md
  duplocloud/resource_duplo_aws_ssm_parameter.go
  duplocloud/resource_duplo_k8_secret.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3, bug_fix

#664 Duplo-21058 TF:Azure:AgentPool: spot_max_price should not allow values less than 0.00001
  CHANGELOG.md
  docs/resources/azure_k8_node_pool.md
  duplocloud/resource_duplo_azure_k8_node_pool.go
Labels: documentation, enhancement, Review effort [1-5]: 3

#662 Duplo-21055 TF:Azure:AgentPool: Resource duplocloud_azure_k8_node_pool allows 'eviction_policy' for 'Regular' type of Scale Set Priority.
  CHANGELOG.md
Labels: documentation, enhancement, Review effort [1-5]: 1, bug_fix

#661 DUPLO-21061 TF:Azure:AgentPool: Parameter 'spot_max_price' should not be supported with 'Scale Set Priority' = 'Regular'
  CHANGELOG.md
Labels: documentation, enhancement, Review effort [1-5]: 1, error handling

#656 DUPLO-18316 nodepool availability zone implementation
  docs/resources/azure_k8_node_pool.md
  duplocloud/resource_duplo_azure_k8_node_pool.go
  duplosdk/azure_node_pool.go
  examples/resources/duplocloud_azure_k8_node_pool/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 2

#647 DUPLO-20525 TF: Enable user to add custom kubernetes labels to nodes
  docs/data-sources/asg_profiles.md
  docs/data-sources/native_hosts.md
  docs/resources/asg_profile.md
  docs/resources/aws_host.md
  duplocloud/resource_duplo_asg_profile.go
  duplocloud/resource_duplo_aws_host.go
  duplosdk/asg.go
  duplosdk/native_hosts.go
  examples/resources/duplocloud_asg_profile/resource.tf
  examples/resources/duplocloud_aws_host/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 2

#635 DUPLO-19625 TF Doc:duplocloud_asg_profile: Add allowed metrics values for `enabled_metrics` parameter and add example in example usage.
  docs/resources/asg_profile.md
  duplocloud/resource_duplo_asg_profile.go
  examples/resources/duplocloud_asg_profile/resource.tf
Labels: documentation, Review effort [1-5]: 2

#668 DUPLO-19625 added validation to enabled_metrics attribute
  CHANGELOG.md
  duplocloud/resource_duplo_asg_profile.go
Labels: documentation, enhancement, Review effort [1-5]: 2

#669 DUPLO-21141 TF:duplocloud_azure_k8_node_pool: Provider plugin crashed when the scale set priority is not specified in Terraform
  CHANGELOG.md
  duplocloud/resource_duplo_azure_k8_node_pool.go
Labels: documentation, Bug fix, Review effort [1-5]: 2, bug_fix

#672 Release v0.10.42
  .github/workflows/finish-release.yml
  .github/workflows/release-publish.yml
  .github/workflows/start-release.yml
  CHANGELOG.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#674 DUPLO-21153 TF:RDS: performance insight: change flag from enable to enabled
  CHANGELOG.md
  docs/resources/rds_instance.md
  duplocloud/resource_duplo_rds_instance.go
  examples/resources/duplocloud_rds_instance/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 2

#675 Release v0.10.43
  CHANGELOG.md
  Makefile
  README.md
  docs/resources/rds_instance.md
  duplocloud/resource_duplo_rds_instance.go
  examples/aws-integration/main.tf
  examples/ecs/main.tf
  examples/eks-integration/main.tf
  examples/emr/files/emr_auto_scaling/main.tf
  examples/emr/files/emr_spot/main.tf
  examples/emr/main.tf
  examples/ephemeral-storage/main.tf
  examples/infrastructure/main.tf
  examples/k8/main.tf
  examples/resources/duplocloud_rds_instance/resource.tf
  examples/service/main.tf
Labels: documentation, enhancement, Review effort [1-5]: 2

#676 Release v0.10.43
  .github/workflows/dev-check.yml
  .github/workflows/finish-release.yml
  .github/workflows/start-release.yml
  CHANGELOG.md
Labels: documentation, enhancement, Review effort [1-5]: 2, configuration changes

#677 DUPLO-21079 Mask SSM parameter of type secret string in terraform logs.
  CHANGELOG.md
  docs/data-sources/aws_ssm_parameter.md
  docs/resources/aws_ssm_parameter.md
  duplocloud/data_source_duplo_aws_ssm_parameter.go
  duplocloud/resource_duplo_aws_ssm_parameter.go
Labels: documentation, enhancement, Review effort [1-5]: 2

#679 Release v0.10.44
  CHANGELOG.md
  Makefile
  docs/data-sources/aws_ssm_parameter.md
  docs/resources/aws_ssm_parameter.md
  duplocloud/data_source_duplo_aws_ssm_parameter.go
  duplocloud/resource_duplo_aws_ssm_parameter.go
  examples/aws-integration/main.tf
  examples/ecs/main.tf
  examples/eks-integration/main.tf
  examples/emr/files/emr_auto_scaling/main.tf
  examples/emr/files/emr_spot/main.tf
  examples/emr/main.tf
  examples/ephemeral-storage/main.tf
  examples/infrastructure/main.tf
  examples/k8/main.tf
  examples/service/main.tf
Labels: documentation, enhancement, Review effort [1-5]: 2

#671 DUPLO-21053 Duplicate scale_priority initialization fix
  CHANGELOG.md
  duplocloud/resource_duplo_azure_k8_node_pool.go
Labels: documentation, Review effort [1-5]: 2, bug_fix

#680 Release v0.10.44
  CHANGELOG.md
  duplocloud/resource_duplo_azure_k8_node_pool.go
Labels: documentation, Bug fix, Review effort [1-5]: 2

#681 Duplo-21171 RDS TF: Performance insight enable is not working for Cluster DB writer instance. it works when enabled through the API.
  CHANGELOG.md
  duplocloud/resource_duplo_rds_instance.go
  examples/resources/duplocloud_rds_instance/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 3

#682 DUPLO-21150: TF Doc: Update doc to include samples for Redis logging configuration
  CHANGELOG.md
  docs/resources/ecache_instance.md
  duplocloud/resource_duplo_ecache_instance.go
  templates/resources/ecache_instance.md.tmpl
Labels: documentation, enhancement, Review effort [1-5]: 2

#683 Release v0.10.45
  CHANGELOG.md
  Makefile
  docs/resources/ecache_instance.md
  duplocloud/resource_duplo_ecache_instance.go
  duplocloud/resource_duplo_rds_instance.go
  examples/aws-integration/main.tf
  examples/ecs/main.tf
  examples/eks-integration/main.tf
  examples/emr/files/emr_auto_scaling/main.tf
  examples/emr/files/emr_spot/main.tf
  examples/emr/main.tf
  examples/ephemeral-storage/main.tf
  examples/infrastructure/main.tf
  examples/k8/main.tf
  examples/resources/duplocloud_rds_instance/resource.tf
  examples/service/main.tf
  templates/resources/ecache_instance.md.tmpl
Labels: documentation, enhancement, Review effort [1-5]: 3

#685 Duplo 21203 Performance Insight Regression
  CHANGELOG.md
  duplocloud/resource_duplo_rds_instance.go
  duplosdk/rds_instance.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#686 DUPLO-21144 TF: duplocloud_azure_k8_node_pool: Updating availability zone should show force replacement of resource in Plan
  CHANGELOG.md
  duplocloud/resource_duplo_azure_k8_node_pool.go
Labels: documentation, enhancement, Review effort [1-5]: 2

#690 DUPLO-21171 hotfix: apply aurora perf insights validation only if performance insights is enabled
  CHANGELOG.md
  duplocloud/resource_duplo_rds_instance.go
Labels: Bug fix, Review effort [1-5]: 2

#692 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation, Review effort [1-5]: 1

#694 DUPLO-21167: add new airflow versions and remove deprecated versions
  CHANGELOG.md
  docs/resources/aws_mwaa_environment.md
  duplocloud/resource_duplo_aws_mwaa_environment.go
Labels: documentation, enhancement, Review effort [1-5]: 2

#699 DUPLO-21234: mwaa takes long time to delete and create, increase timeout
  CHANGELOG.md
  duplocloud/resource_duplo_aws_mwaa_environment.go
Labels: documentation, enhancement, Review effort [1-5]: 1

#697 DUPLO-21184 TF: RDS:DocDB: not able to enable Performance Insight, duplo gives fault for not supported while aws supports
  CHANGELOG.md
  docs/resources/rds_instance.md
  duplocloud/resource_duplo_rds_instance.go
  duplosdk/rds_instance.go
  examples/resources/duplocloud_rds_instance/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 3

#698 DUPLO-21225 TF Doc: RDS: Fix description of performance insights
  CHANGELOG.md
  docs/resources/rds_instance.md
  duplocloud/resource_duplo_rds_instance.go
  templates/resources/rds_instance.md.tmpl
Labels: documentation, enhancement, Review effort [1-5]: 2

#701 DUPLO-21238 chore: port rds perf insights to read replica resource and DUPLO-21184 Fix
  CHANGELOG.md
  docs/resources/rds_read_replica.md
  duplocloud/resource_duplo_rds_instance.go
  duplocloud/resource_duplo_rds_read_replica.go
  duplocloud/utils.go
  duplosdk/rds_instance.go
  examples/resources/duplocloud_rds_read_replica/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 3

#705 DUPLO-21209 DUPLO-21302
  CHANGELOG.md
  docs/resources/rds_instance.md
  docs/resources/rds_read_replica.md
  duplocloud/resource_duplo_rds_instance.go
  duplocloud/resource_duplo_rds_read_replica.go
Labels: documentation, enhancement, Review effort [1-5]: 3

#706 DUPLO-21304 fix: force rds replicas not to have perf insight configuration when they belong in an aurora cluster
  CHANGELOG.md
  docs/resources/rds_read_replica.md
  duplocloud/resource_duplo_rds_read_replica.go
  examples/resources/duplocloud_rds_read_replica/resource.tf
Labels: documentation, Bug fix, Review effort [1-5]: 3

#709 gcp cloud sql resource update
  CHANGELOG.md
  docs/resources/gcp_sql_database_instance.md
  duplocloud/resource_duplo_gcp_sql_database.go
  duplosdk/gcp_sql_database.go
Labels: documentation, enhancement, Review effort [1-5]: 2

#707 DUPLO-21304 DUPLO-21209 Aurora/v2: replica tries to set value as nil for inplace update and inplace update fixes
  CHANGELOG.md
  docs/resources/rds_read_replica.md
  duplocloud/resource_duplo_rds_instance.go
  duplocloud/resource_duplo_rds_read_replica.go
  examples/resources/duplocloud_rds_read_replica/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 3

#704 DUPLO-17188 TF:GCP: allowed to create tenant with google in it
  CHANGELOG.md
  duplocloud/resource_duplo_tenant.go
  duplocloud/utils.go
Labels: documentation, enhancement, Review effort [1-5]: 2

#703 DUPLO-21091 TF:GCP:[ july/Master]: Getting 'postAPI GCPSqlDBInstanceCreate(20e5ec6e-34e6-42f8-add1-4e5fd53362d3, test-develop): cannot unmarshal response from JSON: json: cannot unmarshal array into Go struct field DuploGCPSqlDBInstance.IpAddress of type string' while creating SQL database.
  CHANGELOG.md
  docs/data-sources/gcp_sql_database_instance.md
  docs/data-sources/gcp_sql_database_instances.md
  duplocloud/data_source_duplo_gcp_sql.go
  duplocloud/data_source_duplo_gcp_sqls.go
  duplocloud/resource_duplo_gcp_sql_database.go
  duplocloud/utils.go
Labels: documentation, Bug fix, Review effort [1-5]: 3
