Repository duplocloud/terraform-provider-duplocloud, pull requests merged in 2024-02, with the labels that each got.

#384 DUPLO-13555: Added `is any host allowed` functionality to Job and CronJob
  CHANGELOG.md
  duplocloud/resource_duplo_k8s_cron_job.go
  duplocloud/resource_duplo_k8s_job.go
  duplosdk/k8s_cron_job.go
  duplosdk/k8s_job.go
Labels: enhancement, Review effort [1-5]: 2

#385 fixing bug : DUPLO-11835 -> now adds subnet only when needed (in Azure)
  CHANGELOG.md
  duplocloud/resource_duplo_infrastructure.go
Labels: Bug fix, Review effort [1-5]: 2

#386 DUPLO-14859: add duplocloud client unit tests
  CHANGELOG.md
  duplosdk/client_test.go
Labels: enhancement, Review effort [1-5]: 2, tests

#388 DUPLO-14602 fix: get ASG allocation tags from CustomDataTags instead of MinionTags
  CHANGELOG.md
  duplocloud/data_source_duplo_asg_profile.go
  duplocloud/resource_duplo_asg_profile.go
  duplosdk/asg.go
Labels: enhancement, Bug fix, Review effort [1-5]: 2, bug_fix

#391 DUPLO-14884: support ingress port_name attribute
  CHANGELOG.md
  duplocloud/resource_duplo_k8_ingress.go
  duplosdk/k8s_ingress.go
  examples/k8/main.tf
Labels: enhancement, Review effort [1-5]: 2

#389 DUPLO-14801: SQS Delivery Delay
  CHANGELOG.md
  docs/resources/aws_sqs_queue.md
  duplocloud/resource_duplo_aws_sqs_queue.go
  duplosdk/aws_sqs.go
  examples/resources/duplocloud_aws_sqs_queue/resource.tf
Labels: enhancement, Ready for review, Review effort [1-5]: 4

#396 DUPLO-14932: Fix regression with ingress validation
  CHANGELOG.md
  duplocloud/resource_duplo_k8_ingress.go
Labels: Review effort [1-5]: 1, bug_fix

#394 [DUPLO-14500] - TF: Not able create OpenSearch with (warm enable =false and cold storage=false)
  CHANGELOG.md
  duplocloud/resource_duplo_aws_elasticsearch.go
  duplosdk/aws_elasticsearch.go
Labels: Ready for review, Review effort [1-5]: 2, bug_fix

#393 DUPLO-13194 Support for prepended user data on hosts
  CHANGELOG.md
  docs/data-sources/asg_profiles.md
  docs/data-sources/native_hosts.md
  docs/resources/asg_profile.md
  docs/resources/aws_host.md
  duplocloud/data_source_duplo_asg_profile.go
  duplocloud/data_source_duplo_native_hosts.go
  duplocloud/resource_duplo_asg_profile.go
  duplocloud/resource_duplo_aws_host.go
  duplosdk/asg.go
  duplosdk/native_hosts.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff/compose.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff/computed.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff/condition.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff/doc.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff/force_new.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff/validate.go
  vendor/modules.txt
Labels: enhancement, Ready for review, Review effort [1-5]: 3

#397 DUPLO-6168, DUPLO-13189 fix: update ECS task definition example with AWS supported port mapping field
  CHANGELOG.md
  docs/resources/ecs_task_definition.md
  examples/resources/duplocloud_ecs_task_definition/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 1

#398 DUPLO 14506 Fix for duplocloud_aws_elasticsearch creation without cloud storage o…
  CHANGELOG.md
  duplocloud/resource_duplo_aws_elasticsearch.go
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#400 DUPLO-14967: TF acceptance tests: data.duplocloud_native_hosts
  CHANGELOG.md
  duplocloud/data_source_duplo_native_hosts.go
  duplocloud/data_source_duplo_native_hosts_test.go
  duplocloud/provider_test.go
  duplocloud/resource_duplo_aws_host.go
  duplocloud/resource_duplo_aws_host_test.go
  internal/duplocloudtest/checks.go
  internal/duplosdktest/emulator.go
  internal/duplosdktest/fixtures/tenant/302c6a63-ffc4-4276-b52e-48a84108b658/aws_host/i-a4a64e4407f5ae678.json
Labels: enhancement, Review effort [1-5]: 2, tests

#406 DUPLO-15007: Happy path tests for duplocloud_aws_host
  CHANGELOG.md
  Makefile
  duplocloud/provider_test.go
  duplocloud/resource_duplo_aws_host.go
  duplocloud/resource_duplo_aws_host_test.go
  internal/duplocloudtest/helpers.go
  internal/duplosdktest/emulator.go
  internal/duplosdktest/fixtures.go
  internal/duplosdktest/fixtures/tenant/302c6a63-ffc4-4276-b52e-48a84108b658/aws_host/i-a4a64e4407f5ae678.json
  internal/duplosdktest/fixtures/tenant/302c6a63-ffc4-4276-b52e-48a84108b658/external_subnets/1.json
  internal/duplosdktest/fixtures/tenant/302c6a63-ffc4-4276-b52e-48a84108b658/external_subnets/2.json
  internal/duplosdktest/fixtures/tenant/302c6a63-ffc4-4276-b52e-48a84108b658/internal_subnets/1.json
  internal/duplosdktest/fixtures/tenant/302c6a63-ffc4-4276-b52e-48a84108b658/internal_subnets/2.json
Labels: enhancement, Review effort [1-5]: 3, tests

#407 DUPLO-15049: Unit Tests: Resource: duplocloud_tenant_config
  CHANGELOG.md
  duplocloud/data_source_duplo_tenant_config_test.go
  duplocloud/data_source_duplo_tenant_test.go
  duplocloud/provider_test.go
  duplocloud/resource_duplo_aws_host_test.go
  duplocloud/resource_duplo_tenant_config_test.go
  duplosdk/tenant.go
  internal/duplocloudtest/helpers.go
  internal/duplosdktest/emulator.go
  internal/duplosdktest/fixtures.go
  internal/duplosdktest/fixtures/tenant/302c6a63-ffc4-4276-b52e-48a84108b658/metadata/foo.json
  internal/duplosdktest/fixtures/tenant/302c6a63-ffc4-4276-b52e-48a84108b658/metadata/xyz.json
  internal/duplosdktest/fixtures/tenant/6b2672db-b930-4875-b327-78d9dcbd5dd6.json
Labels: enhancement, Review effort [1-5]: 3, tests

#408 DUPLO-13374 - Add SkipFinalSnapshot support for create and update rds.
  CHANGELOG.md
  docs/resources/rds_instance.md
  duplocloud/resource_duplo_rds_instance.go
  duplosdk/rds_instance.go
Labels: Review effort [1-5]: 3

#409 DUPLO-15103 Bug Fix Plugin crashed when creating opensearch with the warm_enabled set to true
  CHANGELOG.md
  duplocloud/resource_duplo_aws_cloudwatch_event_rule.go
  duplocloud/resource_duplo_aws_elasticsearch.go
Labels: Review effort [1-5]: 2, bug_fix

#411 DUPLO-15096 bug fixed missing elasticsearch version
  CHANGELOG.md
  duplosdk/aws_elasticsearch.go
Labels: Review effort [1-5]: 1, bug_fix

#413 [DUPLO-14500] - TF: Not able create OpenSearch with (warm enable =false and cold storage=false)
  CHANGELOG.md
  duplocloud/resource_duplo_aws_elasticsearch.go
Labels: Review effort [1-5]: 2

#423 DUPLO-11165: Added dead letter queue configuration to AWS lambda
  CHANGELOG.md
  duplocloud/resource_duplo_aws_lambda_function.go
  duplosdk/aws_lambda_function.go
Labels: enhancement, Review effort [1-5]: 3

#412 DUPLO-14936, DUPLO-14934, DUPLO-14935
  CHANGELOG.md
  duplocloud/resource_duplo_aws_efs_file_system.go
  duplocloud/resource_duplo_aws_efs_file_system_lifecycle_policy.go
  duplosdk/aws_efs_lifecycle_policy.go
  examples/resources/duplocloud_aws_efs_lifecycle_policy/import.sh
  examples/resources/duplocloud_aws_efs_lifecycle_policy/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 3, bug_fix

#416 DUPLO-13077 fixes broken elastic search creation with no dedicated master type and fixes elasticsearch_version mapping
  CHANGELOG.md
  duplocloud/resource_duplo_aws_elasticsearch.go
  duplosdk/aws_elasticsearch.go
Labels: Review effort [1-5]: 2, bug_fix

#419 Duplo 11508 RDS secret manager attribute bug fix
  CHANGELOG.md
  duplocloud/resource_duplo_rds_instance.go
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#421 DUPLO-15208 - Fix issue where SkipFinalSnapshot is not included in the JSON on update.
  CHANGELOG.md
  duplosdk/rds_instance.go
Labels: Review effort [1-5]: 2

#417 DUPLO-11669: dynamodb tabl v2 - add point in recovery and delete protection config
  CHANGELOG.md
  docs/resources/aws_dynamodb_table_v2.md
  duplocloud/resource_duplo_aws_dynamodb_table_v2.go
  duplosdk/aws_dynamo_db.go
Labels: enhancement, Review effort [1-5]: 3
