Repository duplocloud/terraform-provider-duplocloud, pull requests merged in 2024-01, with the labels that each got.

#358 DUPLO-13536 feat: exposes fqdn and related variables for duplo service
  duplocloud/data_source_duplo_service.go
  duplocloud/resource_duplo_service.go
  duplosdk/replication_controller.go
Labels: Ready for review

#359 DUPLO feat: allow provider development with debuggers
  .gitignore
  .vscode/launch.json
  README.md
  main.go
Labels: Ready for review

#360 DUPLO-13203 support for duplocloud_aws_host.allocated_public_ip
  duplocloud/resource_duplo_aws_host.go
Labels: Ready for review

#365 DUPLO-12731, DUPLO-12732: k8s job - env, command, args, init_container
  docs/data-sources/duplo_service.md
  docs/data-sources/duplo_services.md
  docs/data-sources/plan_settings.md
  docs/resources/duplo_service.md
  docs/resources/rds_instance.md
  duplocloud/structures_k8s.go
  duplocloud/structures_k8s_container.go
  duplocloud/structures_k8s_pod.go
  examples/resources/duplocloud_rds_instance/resource.tf
Labels: Ready for review

#366 DUPLO-12737 & DUPLO-14306: k8s job fixes
  docs/data-sources/k8s_job.md
  duplocloud/data_source_duplo_k8s_cron_job.go
  duplocloud/data_source_duplo_k8s_job.go
  duplocloud/provider.go
  duplocloud/resource_duplo_k8s_cron_job.go
  duplocloud/resource_duplo_k8s_job.go
  duplocloud/schema_k8s_metadata.go
  duplocloud/structure_cron_job_v1beta1.go
  duplocloud/structure_k8s_job.go
  duplocloud/structures_k8s_pod.go
  duplosdk/k8s_job.go
  examples/data-sources/duplocloud_k8s_cron_job/data-source.tf
  examples/data-sources/duplocloud_k8s_job/data-source.tf
Labels: Ready for review

#374 DUPLO-14181 fix: add "ImplementationSpecific" to list of possible values for ingress rule path types
  CHANGELOG.md
  duplocloud/resource_duplo_k8_ingress.go
Labels: Bug fix

#363 DUPLO-13452 feat: include can_scale_from_zero flag in ASG profile
  CHANGELOG.md
  duplocloud/resource_duplo_asg_profile.go
  duplosdk/asg.go
Labels: enhancement, Review effort [1-5]: 2

#376 DUPLO-1389 fix: update provider docs for ECS service and task definition
  CHANGELOG.md
  docs/resources/ecs_service.md
  docs/resources/ecs_task_definition.md
  examples/resources/duplocloud_ecs_service/resource.tf
  examples/resources/duplocloud_ecs_task_definition/resource.tf
Labels: documentation, Review effort [1-5]: 1

#375 DUPLO-13674: added is_serverless_kubernetes property in infrastructure
  CHANGELOG.md
  README.md
  duplocloud/resource_duplo_infrastructure.go
  duplosdk/infrastructure.go
Labels: enhancement, Review effort [1-5]: 2

#377 DUPLO-14597: forces recreation on changes to is_cluster_autoscaled and can_scale_from_zero
  CHANGELOG.md
  duplocloud/data_source_duplo_tenant.go
  duplocloud/resource_duplo_asg_profile.go
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#378 [DUPLO-14321] : TF: Doc: duplocloud_duplo_service, cloud parameter value for gcp missing
  CHANGELOG.md
  docs/data-sources/asg_profiles.md
  docs/resources/asg_profile.md
  docs/resources/duplo_service.md
  docs/resources/infrastructure.md
  duplocloud/resource_duplo_service.go
Labels: documentation, enhancement, Review effort [1-5]: 1

#379 DUPLO-4661: Tag based resource handling for lambda function and S3 resource.
  CHANGELOG.md
  duplocloud/resource_duplo_aws_lambda_function.go
  duplocloud/resource_duplo_s3_bucket.go
  duplosdk/admin.go
  duplosdk/tenant_aws_cloud_resources.go
Labels: enhancement, Review effort [1-5]: 3
