Repository duplocloud/terraform-provider-duplocloud, pull requests merged in 2024-08, with the labels that each got.

#621 DUPLO-20452 Infra Setting document fix
  docs/resources/infrastructure_setting.md
  duplocloud/resource_duplo_infrastructure_setting.go
Labels: documentation, enhancement, Review effort [1-5]: 2

#595 DUPLO-17963 feat: add support for asynchronous retry features to duplocloud provider
  CHANGELOG.md
  docs/resources/aws_lambda_function_event_config.md
  duplocloud/provider.go
  duplocloud/resource_duplo_aws_lambda_function_event_config.go
  duplosdk/aws_lambda_function.go
  examples/resources/duplocloud_aws_lambda_function_event_config/import.sh
  examples/resources/duplocloud_aws_lambda_function_event_config/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 4

#632 DUPLO-17855 feat: integrate dead letter queue support for sqs on TF provider
  CHANGELOG.md
  docs/resources/aws_sqs_queue.md
  duplocloud/resource_duplo_aws_sqs_queue.go
  duplosdk/aws_sqs.go
  examples/resources/duplocloud_aws_sqs_queue/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 3

#641 Revert "DUPLO-20879 Fallback implemented"
  CHANGELOG.md
  duplocloud/resource_duplo_aws_dynamodb_table_v2.go
Labels: Bug fix, Review effort [1-5]: 2

#648 DUPLO-20918: [Avialabilty Zone] RDS primary and replica to support AZ zone
  CHANGELOG.md
  docs/resources/rds_instance.md
  duplocloud/resource_duplo_rds_instance.go
  examples/resources/duplocloud_rds_instance/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 2
