Repository duplocloud/terraform-provider-duplocloud, pull requests merged in 2024-04, with the labels that each got.

#476 DUPLO-16672: Azure TF> duplocloud_azure_virtual_machine resource apply fails with an error when prefixes are enabled
  CHANGELOG.md
  docs/resources/azure_virtual_machine.md
  duplocloud/resource_duplo_azure_virtual_machine.go
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#478 Duplo 15896 kube error msg fixed nil pointer exception
  CHANGELOG.md
  duplocloud/data_source_duplo_eks_credentials.go
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#479 Duplo 15896 kube error msg for GKE datasource
  CHANGELOG.md
  duplocloud/data_source_duplo_gke_credentials.go
  duplocloud/resource_duplo_lbconfigs.go
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#483 DUPLO-16704 FIX GKE DATASOURCE EXAMPLE
  CHANGELOG.md
  docs/data-sources/gke_credentials.md
  examples/data-sources/duplocloud_gke_credentials/data-source.tf
Labels: documentation, enhancement, Review effort [1-5]: 1

#488 DUPLO-15011 DUPLO-16144: TF: Force recreate tf resource when volume mapping is modified for duplo service in terraform (contextual)
  CHANGELOG.md
  duplocloud/resource_duplo_service.go
  duplosdk/replication_controller.go
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#496 DUPLO 16595 Bug fix on update of taskdefnition
  CHANGELOG.md
  duplocloud/resource_duplo_ecs_service.go
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#475 DUPLO-14760 Mandatory field "Root Password" for database creation is missing for Cloud SQL databases.
  CHANGELOG.md
  docs/resources/gcp_sql_database_instance.md
  duplocloud/resource_duplo_gcp_sql_database.go
  duplosdk/gcp_sql_database.go
Labels: documentation, enhancement, Review effort [1-5]: 3

#485 DUPLO 11726 removed use_launch_template attribute form duplocloud_asg_profile
  docs/data-sources/asg_profiles.md
  docs/resources/asg_profile.md
  duplocloud/resource_duplo_asg_profile.go
  duplosdk/asg.go
Labels: documentation, enhancement, Review effort [1-5]: 2

#480 Duplo 16671 gcp application load balancer global access support
  CHANGELOG.md
  docs/data-sources/duplo_service_lbconfigs.md
  docs/resources/duplo_service_lbconfigs.md
  duplocloud/resource_duplo_lbconfigs.go
  duplosdk/replication_controller.go
  duplosdk/tenant_aws_cloud_resources.go
Labels: documentation, enhancement, Review effort [1-5]: 3

#484 Duplo 16117 Nodepool List Datasource Fix
  CHANGELOG.md
  docs/data-sources/gcp_node_pools.md
  duplocloud/data_source_duplo_gcp_node_pools.go
  duplocloud/resource_duplo_gcp_k8_node_pool.go
  examples/data-sources/duplocloud_gcp_node_pools/data-source.tf
  examples/data-sources/duplocloud_gcp_sqls/data-source.tf
Labels: documentation, enhancement, Review effort [1-5]: 3, bug_fix

#492 Duplo 16561 GCP Firestore Resource
  CHANGELOG.md
  docs/data-sources/gcp_firestore.md
  docs/data-sources/gcp_firestores.md
  docs/resources/gcp_firestore.md
  duplocloud/data_source_duplo_gcp_firestore.go
  duplocloud/data_source_duplo_gcp_firestores.go
  duplocloud/provider.go
  duplocloud/resource_duplo_gcp_firestore.go
  duplosdk/gcp_firestore.go
  examples/data-sources/duplocloud_gcp_firestore/data-source.tf
  examples/data-sources/duplocloud_gcp_firestores/data-source.tf
  examples/resources/duplocloud_gcp_firestore/import.sh
  examples/resources/duplocloud_gcp_firestore/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 4

#493 DUPLO-15896 fix for duplocloud_eks_credentials data-source related to azure
  CHANGELOG.md
  duplocloud/data_source_duplo_eks_credentials.go
  duplocloud/data_source_duplo_gke_credentials.go
  duplosdk/infrastructure.go
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#487 DUPLO-16114 feat: add exponential backoff to lb methods with low AWS rate limits
  CHANGELOG.md
  duplosdk/agnostic_load_balancer.go
  duplosdk/utils.go
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#510 DUPLO-11667: TF: duplocloud_admin_system_setting.DBInstanceParameter gives Provider produced inconsistent result after apply error
  CHANGELOG.md
  build.sh
  docs/resources/admin_system_setting.md
  duplocloud/resource_duplo_admin_system_setting.go
  duplosdk/utils.go
  examples/resources/duplocloud_admin_system_setting/import.sh
Labels: enhancement, Review effort [1-5]: 3, bug_fix
