Repository duplocloud/terraform-provider-duplocloud, pull requests merged in 2024-05, with the labels that each got.

#515 Duplo 8942/dynamo table updates
  duplocloud/resource_duplo_aws_dynamodb_table_v2.go
  duplosdk/aws_dynamo_db.go
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#516 DUPLO-14998 Updated default value and docs
  docs/resources/asg_profile.md
  docs/resources/aws_host.md
  duplocloud/resource_duplo_aws_host.go
Labels: documentation, enhancement, Review effort [1-5]: 2

#509 DUPLO-17034 Mount targets details are missing in TF state file
  duplocloud/resource_duplo_aws_efs_file_system.go
  duplosdk/aws_efs.go
  duplosdk/aws_efs_lifecycle_policy.go
Labels: enhancement, Review effort [1-5]: 3

#544 [DUPLO-17469, DUPLO-17888] fix: adjust duplo client timeout and include timeout error in retriable error check for TenantUpdateLbSettings
  duplocloud/resource_duplo_service_params.go
  duplosdk/agnostic_load_balancer.go
  duplosdk/client.go
  duplosdk/replication_controller.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3
