Repository duplocloud/terraform-provider-duplocloud, pull requests merged in 2024-03, with the labels that each got.

#415 Duplo 14623 DUPLO GCP Node Pool implementation
  .gitignore
  CHANGELOG.md
  docs/resources/gcp_node_pool.md
  duplocloud/provider.go
  duplocloud/resource_duplo_gcp_k8_node_pool.go
  duplosdk/gcp_node_pools.go
  examples/resources/duplocloud_gcp_node_pool/import.sh
  examples/resources/duplocloud_gcp_node_pool/resource.tf
Labels: enhancement, Review effort [1-5]: 4

#424 Duplo 11675 RDS Group Cluster Parameter support
  CHANGELOG.md
  docs/resources/rds_instance.md
  duplocloud/resource_duplo_rds_instance.go
  duplosdk/rds_instance.go
  examples/resources/duplocloud_rds_instance/resource.tf
Labels: documentation, enhancement, Review effort [1-5]: 3

#435 DUPLO-15716: Getting error for EFS lifecycle policy "cannot unmarshal response from JSON: unexpected end of JSON input"
  CHANGELOG.md
  duplocloud/resource_duplo_aws_efs_file_system.go
  duplocloud/resource_duplo_aws_efs_file_system_lifecycle_policy.go
  duplosdk/aws_efs_lifecycle_policy.go
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#425 Duplo 13405 Terraform provider - duplocloud batch job definitions with revisions do not delete correctly
  CHANGELOG.md
  duplocloud/resource_duplo_aws_batch_job_definition.go
  duplosdk/aws_batch.go
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#449 DUPLO-14315: added architecture field to lambda function
  CHANGELOG.md
  duplocloud/resource_duplo_aws_lambda_function.go
  duplosdk/aws_lambda_function.go
Labels: enhancement, Review effort [1-5]: 2

#446 DUPLO-15817 docs usage of cache_policy_id for cloudfront resource
  CHANGELOG.md
  docs/resources/aws_cloudfront_distribution.md
  duplocloud/resource_duplo_aws_cloudfront_distribution.go
Labels: documentation, enhancement, Review effort [1-5]: 3

#431 DUPLO-10189: v3 api s3
  CHANGELOG.md
  docs/resources/s3_bucket.md
  duplocloud/resource_duplo_s3_bucket.go
  duplosdk/tenant_aws_cloud_resources.go
  examples/resources/duplocloud_s3_bucket/resource.tf
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#467 HH2 azure fixes
  CHANGELOG.md
  duplocloud/provider_test.go
  duplocloud/resource_duplo_azure_storage_account.go
  duplocloud/resource_duplo_infrastructure.go
  duplocloud/resource_duplo_infrastructure_subnet.go
  duplocloud/resource_duplo_tenant.go
  duplosdk/admin.go
  duplosdk/tenant.go
  internal/duplosdktest/emulator.go
  internal/duplosdktest/fixtures/infra/testacc1.json
Labels: enhancement, do not merge, Review effort [1-5]: 4, bug_fix

#469 Duplo-16551 fixed.
  CHANGELOG.md
  duplocloud/resource_duplo_infrastructure.go
Labels: enhancement, Review effort [1-5]: 2

#470 DUPLO-16461 Fixed
  CHANGELOG.md
  docs/resources/azure_storage_account.md
  docs/resources/infrastructure.md
  duplocloud/resource_duplo_azure_storage_account.go
Labels: documentation, enhancement, Review effort [1-5]: 2
